### ISSUE TITLE
@conda-forge-admin please add user @djhoese

### ISSUE THREAD

**Issue by djhoese** [conda-forge/influxdb-client-feedstock#13]
### Additional comment:

I'd like to make a conda environment with the newest version of this library, but it seems to be unmaintained. I'm hoping once the builds get fixed it'll just be enabling auto-merge for any future releases.

**Comment by ruben-arts** [comment]
He that's fair, completely forgotten this, the issue was that this package added a depenency that was not available on conda-forge yet and as we didn't need a higher version I lost this out of sight. Will try to do this as soon as possible (no dev PC atm).

**Comment by djhoese** [comment]
Thanks for the info @ruben-arts. What was the dependency? Any idea if it is available on conda-forge now?

**Comment by ruben-arts** [comment]
Yes working on it right now. It was `reactivex` https://github.com/conda-forge/staged-recipes/pull/22223

When that is published to conda-forge I can restart the ci's of this feedstock :crossed_fingers:

**Comment by djhoese** [comment]
I won't have permission to restart anything. This PR needs to be merged (by you or conda-forge core) for me to get added as a maintainer: https://github.com/conda-forge/influxdb-client-feedstock/pull/14

**Comment by djhoese** [comment]
Hm or maybe I can if I use the conda-forge bot commands. Anyway...if you've got this figured out maybe I'll just stay not a maintainer.
